# Generated by Django 3.2.4 on 2021-06-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrizacion', '0003_alter_parametrizacion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrizacion',
            name='valor',
            field=models.CharField(max_length=250),
        ),
    ]
