# Generated by Django 3.1.7 on 2021-05-12 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_identificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tipo_identificacion', models.TextField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tipo_usuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(choices=[(1, 'Paciente'), (2, 'Funcionario'), (3, 'Administrador')], null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.tipo_usuario'),
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RH', models.TextField(max_length=3)),
                ('sexo', models.CharField(max_length=1)),
                ('numero_identificacion', models.TextField(max_length=15)),
                ('tipo_identificacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.tipo_identificacion')),
                ('usuario_p', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
