# Generated by Django 3.1.7 on 2021-06-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0003_alter_auditoria_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
