# Generated by Django 3.2.4 on 2021-06-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0005_alter_auditoria_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
